# -*- coding: utf-8 -*-
"""Implied_vol_screener.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WYPQai2E-_z-SvFDeCT_rJwrjqfj4nvu
"""

import yfinance as yf
import pandas as pd
import numpy as np
from datetime import datetime

###########################################################################
# PARAMETERS
###########################################################################

START_DATE = "2021-01-01"

###########################################################################
# PRICE STATISTICS
###########################################################################

def get_price_statistics(price_history):

    results = {}

    if price_history.empty:
        return None

    prices = price_history["Adj Close"]

    daily_returns = prices.pct_change().dropna()

    # 1-Year Historical Volatility (252 trading days)
    hv = daily_returns.rolling(252).std() * np.sqrt(252)

    results["Historical Volatility"] = (
        hv.iloc[-1] if not hv.dropna().empty else np.nan
    )
    
    if "High" in price_history and "Low" in price_history and "Close" in price_history:
        hl_c = (price_history["High"] - price_history["Low"]) / price_history["Close"]
        
        avg_10 = hl_c.rolling(10).mean()
        avg_30 = hl_c.rolling(30).mean()
        
        results["10-Day (H-L)/C"] = avg_10.iloc[-1] if not avg_10.dropna().empty else np.nan
        results["30-Day (H-L)/C"] = avg_30.iloc[-1] if not avg_30.dropna().empty else np.nan
        
        if not np.isnan(results["30-Day (H-L)/C"]) and results["30-Day (H-L)/C"] != 0:
            results["10-Day / 30-Day (H-L)/C"] = results["10-Day (H-L)/C"] / results["30-Day (H-L)/C"]
        else:
            results["10-Day / 30-Day (H-L)/C"] = np.nan

    # Approximate 3-year return (750 trading days)
    period = min(750, len(prices)-1)

    if period > 0:
        results["3-Year Return"] = (
            prices.iloc[-1] / prices.iloc[-period-1] - 1
        )
    else:
        results["3-Year Return"] = np.nan

    return results


###########################################################################
# OPTION STATISTICS
###########################################################################

def get_option_statistics(ticker, current_price):

    today = datetime.today()

    expirations = []

    for exp in ticker.options:

        dte = (datetime.strptime(exp,"%Y-%m-%d")-today).days

        if dte >= 7:
            expirations.append((exp,dte))

    if len(expirations)==0:
        return {}

    expiration,dte = min(
        expirations,
        key=lambda x: abs(x[1]-12)
    )

    puts = ticker.option_chain(expiration).puts.copy()

    # First OTM put
    otm = puts[puts["strike"] <= current_price]

    if len(otm):

        strike = otm["strike"].max()
        option = otm.loc[
            otm["strike"]==strike
        ].iloc[0]

    else:

        puts["distance"] = abs(
            puts["strike"]-current_price
        )

        option = puts.loc[
            puts["distance"].idxmin()
        ]

        strike = option["strike"]

    bid = option["bid"]
    ask = option["ask"]

    midpoint = (bid+ask)/2

    collateral = strike-midpoint

    annualized_yield = np.nan

    if collateral>0:

        annualized_yield = (
            midpoint /
            collateral *
            365/dte
        )

    spread_pct = np.nan

    if midpoint>0:

        spread_pct = (
            ask-bid
        )/midpoint

    premium_pct = midpoint/strike

    otm_pct = (
        current_price-strike
    )/current_price

    return {

        "Expiration":expiration,
        "DTE":dte,

        "Strike":strike,

        "Bid":bid,
        "Ask":ask,
        "Midpoint":midpoint,

        "Implied Volatility":
            option["impliedVolatility"],

        "Premium %":
            premium_pct,

        "OTM %":
            otm_pct,

        "Annualized Yield":
            annualized_yield,

        "Bid/Ask Spread %":
            spread_pct,

        "Option Volume":
            option["volume"],

        "Open Interest":
            option["openInterest"]

    }


###########################################################################
# MAIN SCREENER
###########################################################################

import concurrent.futures

import time
import random

def process_single_ticker(symbol, price_data):
    max_retries = 3
    for attempt in range(max_retries):
        try:
            # Safely extract price data strictly using Close
            if isinstance(price_data.columns, pd.MultiIndex):
                high_df = price_data["High"] if "High" in price_data.columns.levels[0] else None
                low_df = price_data["Low"] if "Low" in price_data.columns.levels[0] else None
                close_df = price_data["Close"] if "Close" in price_data.columns.levels[0] else None
        
                high = high_df[symbol] if high_df is not None and symbol in high_df.columns else pd.Series(dtype=float)
                low = low_df[symbol] if low_df is not None and symbol in low_df.columns else pd.Series(dtype=float)
                close = close_df[symbol] if close_df is not None and symbol in close_df.columns else pd.Series(dtype=float)
            else:
                # Fallback for old yfinance single-ticker behavior
                high = price_data["High"] if "High" in price_data.columns else pd.Series(dtype=float)
                low = price_data["Low"] if "Low" in price_data.columns else pd.Series(dtype=float)
                close = price_data["Close"] if "Close" in price_data.columns else pd.Series(dtype=float)
        
            print(f"Processing {symbol}")
            row = {"Ticker": symbol}
        
            ticker = yf.Ticker(symbol)
            info = ticker.info
        
            market_cap = info.get("marketCap")
            enterprise_value = info.get("enterpriseValue")
        
            row["Company Name"] = info.get("shortName") or info.get("longName")
            row["Sector"] = info.get("sector")
            row["Industry"] = info.get("industry")
            row["52-Week High"] = info.get("fiftyTwoWeekHigh")
            row["52-Week Low"] = info.get("fiftyTwoWeekLow")
        
            row["Market Cap"] = market_cap
            row["Enterprise Value"] = enterprise_value
        
            if market_cap is not None and enterprise_value is not None and enterprise_value > 0:
                leverage = market_cap / enterprise_value
            else:
                leverage = np.nan
        
            row["Market Cap / EV"] = leverage
        
            # Get next earnings date from calendar if available
            next_earnings = "N/A"
            calendar = ticker.calendar
            if isinstance(calendar, dict) and "Earnings Date" in calendar:
                dates = calendar["Earnings Date"]
                if dates and len(dates) > 0:
                    import datetime
                    # format the date
                    next_earnings = dates[0].strftime("%Y-%m-%d") if isinstance(dates[0], datetime.date) else str(dates[0])
            row["Next Earnings"] = next_earnings
        
            history = pd.DataFrame({
                "Adj Close": close,
                "High": high,
                "Low": low,
                "Close": close
            }).dropna()
            if history.empty:
                return None
        
            current_price = history["Adj Close"].iloc[-1]
            row["Current Price"] = current_price
        
            stats = get_price_statistics(history)
            if stats:
                row.update(stats)
        
            if not np.isnan(leverage) and "Historical Volatility" in row and not np.isnan(row["Historical Volatility"]):
                row["EV Volatility"] = leverage * row["Historical Volatility"]
            else:
                row["EV Volatility"] = np.nan
        
            option_stats = get_option_statistics(ticker, current_price)
            row.update(option_stats)
        
            hv = row.get("Historical Volatility", np.nan)
            iv = row.get("Implied Volatility", np.nan)
        
            if not np.isnan(hv) and hv > 0 and not np.isnan(iv):
                row["IV / HV"] = iv / hv
            else:
                row["IV / HV"] = np.nan
        
            return row
        
        except Exception as e:
            if "Too Many Requests" in str(e) or "Rate limited" in str(e):
                if attempt < max_retries - 1:
                    time.sleep(random.uniform(2, 5))
                    continue
            print(f"Error processing {symbol}: {e}")
            return None

def option_screen(ticker_list, max_workers=5):
    print(f"Downloading historical data for {len(ticker_list)} tickers...")
    price_data = yf.download(
        ticker_list,
        start=START_DATE,
        auto_adjust=False,
        progress=False,
        threads=True
    )

    all_results = []

    print(f"Fetching options data using {max_workers} threads...")
    with concurrent.futures.ThreadPoolExecutor(max_workers=max_workers) as executor:
        futures = {executor.submit(process_single_ticker, symbol, price_data): symbol for symbol in ticker_list}
        for future in concurrent.futures.as_completed(futures):
            result = future.result()
            if result is not None:
                all_results.append(result)

    df = pd.DataFrame(all_results)
    if df.empty:
        return df

    columns = [
        "Ticker", "Company Name", "Sector", "Industry", "Current Price",
        "Next Earnings", "52-Week High", "52-Week Low",
        "Market Cap", "Enterprise Value", "Market Cap / EV",
        "Historical Volatility", "Implied Volatility", "IV / HV", "EV Volatility",
        "10-Day (H-L)/C", "30-Day (H-L)/C", "10-Day / 30-Day (H-L)/C",
        "3-Year Return", "Expiration", "DTE", "Strike",
        "Bid", "Ask", "Midpoint", "Premium %", "OTM %", "Annualized Yield",
        "Bid/Ask Spread %", "Option Volume", "Open Interest"
    ]

    columns = [c for c in columns if c in df.columns]
    df = df[columns]

    return df